# Generated by Django 5.0.3 on 2024-03-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='CreationDate',
            field=models.DateField(default='2024-03-20', null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Postingdate',
            field=models.DateField(default='2024-03-20', null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='CreationDate',
            field=models.DateField(default='2024-03-20', null=True),
        ),
    ]
