# Generated by Django 5.0.3 on 2024-03-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_employees_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='Srno',
            new_name='leaveID',
        ),
    ]
