# Generated by Django 5.0.3 on 2024-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_srno_leave_leaveid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='EmpID',
        ),
        migrations.AddField(
            model_name='leave',
            name='Employee',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
