# Generated by Django 5.0.3 on 2024-03-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_leave_empid_leave_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='Employee',
        ),
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
