# Generated by Django 5.0.3 on 2024-03-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_leave_employee_leave_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='CreationDate',
            field=models.DateField(default='2024-03-21', null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Postingdate',
            field=models.DateField(default='2024-03-21', null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='CreationDate',
            field=models.DateField(default='2024-03-21', null=True),
        ),
    ]
