# Generated by Django 5.0.3 on 2024-03-21 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_department_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.department'),
        ),
    ]
